Added function to clone the original dataset but something is broken
When augmenting it has an issue interpreting the jps
```
ValueError: Can not convert from object to uint8.
```